### ISSUE TITLE
When run composer install following error occur

### ISSUE THREAD

**Issue by AdnanLatif** [tcs-udemy/introduction-to-unit-testing#27]
I tried with fresh installations of Ubuntu 14.04 and Ubuntu 16.04. When I run composer install command following error occur.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gd.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_pgsql.ini
    - /etc/php/7.0/cli/conf.d/20-pgsql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-xdebug.ini
  You can also run `php --ini` inside terminal to see which files are used by PH
P in CLI mode.

**Comment by tsawler** [comment]
It looks like you don’t have PHP installed. You should probably install version 7.2, which you can do as follows (one line per command, followed by return, obviously):

sudo apt-get update

sudo add-apt-repository -y ppa:ondrej/php

sudo apt-get update -y

sudo apt-get install php7.2 php7.2-cli php7.2-common php7.2-curl php7.2-pgsql php7.2-fpm php7.2-gd php7.2-imap php7.2-intl php7.2-json php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-readline php7.2-soap php7.2-xml php7.2-zip

There are things you don’t need, but they won’t hurt.



--
Trevor Sawler, Ph.D.
Verilion Inc.
trevor.sawler@verilion.com
506.474.2804

**Comment by AdnanLatif** [comment]
Thanks a lot Trevor. Your solution works like a charm.
